### PR TITLE
新增日文README文件及在现有README中添加链接

### PR DESCRIPTION
**Pull request by dfaw20**
本次提交新增了日文版README，并在现有的README文件中添加了指向日文README的链接，方便日语用户阅读。

### CODE REVIEW

**Comment by U1805** [comment]
好好 感谢翻译 (*´∀`)~♥

**Comment by U1805** [comment]
你好，我想着要不要把 How-to-use.md 也按语言拆开，有兴趣写一份日文的吗 (=´ω`=)

**Comment by dfaw20** [comment]
@U1805 

Hello,

Thank you for the merge! 
I am オタク from Japan who loves Blue Archive.

I have opened an issue ( #23 ) for localizing `How-to-use.md` into Japanese👍

If there are any other tasks, I would like to contribute to the development of this project's features

 (I don't understand Chinese, so I will use English)

**Comment by U1805** [comment]
Hello, thank you once again for your help with localization. I've always wanted to add Japanese documentation but was worried about expressing it correctly, so I've put it off until now. I truly appreciate your support!

In the latest commit, I've split the `How-to-use` document. Now, you only need to add a Japanese version called `How-to-use-jp.md` and update the link in `README-jp`.

The project currently has essentially all the features I envisioned, so any future updates will likely be based on user feedback.

If you are willing, could you provide some nicknames or abbreviations used by Japanese players for game characters? I am unsure how to clearly explain this usage. (ノдT)

For example, `イロハ` is sometimes called `168`, `ノノミ` is referred to as `nnm`, `カズサ` is called `黑猫`, and `砂狼シロコ (水着)` is called `水白子` in Chinese (`水` is the abbreviation for the swimsuit skin, translating to 砂狼シロコ (水着) -> 水白子/泳裝白子). 

This feature might not be needed by speakers of other languages since Blue Archive character names are in katakana, and Chinese players name characters in Chinese characters based on phonetics, which leads to a character having many different names (e.g., Yukari is currently the most confusing, with names like "紫", "紫草", "紫蓠", "紫璃", "缘里", "由佳里", "由加里" etc.). Using nicknames to refer to a character is a good solution, and hence this feature was implemented in the project’s search functionality. If this is not needed, then there is no trouble at all. 

If it is needed and you would like to help, I might open an issue or discussion to collect nicknames or abbreviations in various languages later.

**Pull request merged**
